[definition.vec]
headers = ["generic_sources/header/vec_C__PREFIX__.h__TEMPLATE__"]
sources = ["generic_sources/src/vec_C__PREFIX__.c__TEMPLATE__"]
replace.C__TYPENAME__ = "type"
replace.C__TYPEHEADER__ = "header_include"
replace.C__PREFIX__ = "prefix"
replace.C__PREFIXUP__ = "prefix"


[definition.hashmap]
headers = ["generic_sources/header/hashmap_C__PREFIX__.h__TEMPLATE__"]
sources = [
	"generic_sources/src/hashmap_C__PREFIX__.c__TEMPLATE__",
	"generic_sources/src/hashmap_C__PREFIX___utils.c__TEMPLATE__",
]
replace.C__VALTYPE__ = "type"
replace.C__KEYTYPE__ = "type"
replace.C__TYPEHEADER__ = "header_include"
replace.C__PREFIX__ = "prefix"
replace.C__PREFIXUP__ = "prefix"

[[create.hashmap]]
headers_output = "include/me/hashmap/"
sources_output = "src/hashmap/"
replace.C__VALTYPE__ = "t_str"
replace.C__KEYTYPE__ = "t_str"
replace.C__TYPEHEADER__ = ''
replace.C__PREFIX__ = "str"
replace.C__PREFIXUP__ = "STR"

[[create.vec]]
sources_output = "src/vec/"
headers_output = "include/me/vec/"
replace.C__TYPENAME__ = "t_str"
replace.C__TYPEHEADER__ = ''
replace.C__PREFIX__ = "str"
replace.C__PREFIXUP__ = "STR"
